server:
  port: 9030
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable-intelligence-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  ai:
    model.chat: openai
    openai:
      api-key: ${AI_API_KEY:dummy-key}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: google/gemini-3-flash-preview
          temperature: 0.2
      embedding:
        options:
          model: qwen/qwen3-embedding-8b

---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://pgvector.lovable-core.svc.cluster.local:5432/intelligence_db
    username: intelligence_user
    password: ${DB_PASSWORD}

ai:
    openai:
      api-key: ${AI_API_KEY}
    chat:
        options:
          model: google/gemini-3-flash-preview
---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/lovable-intelligence-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      api-key: ${AI_API_KEY:dummy-key}
